services:
  # 1. PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: postgres_compose
    restart: always
    environment:
      POSTGRES_DB: loopin
      POSTGRES_USER: loopin_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  # 2. Redis
  redis:
    image: redis:alpine
    container_name: redis_compose
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  # 3. Spring Boot
  springboot:
    build: .
    container_name: springboot_compose
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loopin
      SPRING_DATASOURCE_USERNAME: loopin_user
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  # 4. nginx
  nginx:
    image: nginx:latest
    container_name: nginx_compose
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - springboot
