spring:
  application:
    name: loopin-backend

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/loopin
    username: loopin_user
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariPool

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000

jwt:
  key: 7b455ca1eb61dabeefdf833d58563a0a88c45473df53c010f841a36edb30f4a8
  access-token-validity: 86400000   # 1일
  refresh-token-validity: 604800000 # 7일

logging:
  level:
    root: INFO
    com.loopin.api.loopinbackend: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
